apiVersion: apps/v1 
kind: Deployment
metadata:
  name: regapp-deployment
  labels: 
     app: regapp

spec:
  replicas: 2 
  selector:
    matchLabels:
      app: regapp

  template:
    metadata:
      labels:
        app: regapp
    spec:
      containers:
      - name: regapp
        #image: 975050130448.dkr.ecr.us-east-1.amazonaws.com/demo:15
        image: rameshadapaka/nodeapp:21
        imagePullPolicy: Always
        ports:
        #- containerPort: 8080
        - containerPort: 3000
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

---
apiVersion: v1
kind: Service
metadata:
  name: regapp-service
  labels:
    app: regapp 
spec:
  selector:
    app: regapp 

  ports:
    - port: 3000
      targetPort: 3000

  type: NodePort
